### ISSUE TITLE
Publish updated Nuget 

### ISSUE THREAD

**Issue by sushihangover** [ghuntley/Cake.AppleSimulator#5]
Publish an updated Nuget with the changes from PR's #2, #3, & #4

https://github.com/sushihangover/Cake.AppleSimulator/issues/9

https://github.com/sushihangover/Cake.AppleSimulator/issues/10

**Comment by gep13** [comment]
@sushihangover @ghuntley just a thought as well...

Since there are now two of you working on this project, would it make sense to move it under the Cake-Contrib Organisation?

http://cakebuild.net/blog/2016/08/cake-contribution-organization

**Comment by sushihangover** [comment]
@gep13 , I have no problem with that, but it is @ghuntley 's repo so I'll defer any decision regarding this to him

**Comment by ghuntley** [comment]
@sushihangover CI issues have been resolved v0.1.0 has been published to NuGet.org; if it lets us down again then yeah let's look at moving to the Cake-Contrib organization.

See https://github.com/ghuntley/Cake.AppleSimulator/releases for release notes. Can you please unlist your package?
